# Generated by Django 3.0.3 on 2020-05-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_auto_20190726_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_sem', models.CharField(choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], max_length=8)),
                ('select_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Course')),
                ('sem_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CS5A', to='info.Class')),
            ],
        ),
        migrations.CreateModel(
            name='SemStudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(default=6.5)),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Sem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Student')),
            ],
            options={
                'ordering': ['sem'],
            },
        ),
        migrations.CreateModel(
            name='SemMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('O(Outstanding)', 'O(Outstanding)'), ('A+(Excellent)', 'A+(Excellent)'), ('A(Very Good)', 'A(Very Good)'), ('B+(Good)', 'B+(Good)'), ('B(Average)', 'B(Average)'), ('C(Pass)', 'C(Pass)'), ('F(Fail)', 'F(Fail)'), ('AB(Absent)', 'AB(Absent)')], max_length=20)),
                ('student_sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.SemStudentCourse')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Course')),
            ],
            options={
                'ordering': ['student_sem__sem'],
            },
        ),
    ]
