# Generated by Django 3.0.3 on 2020-05-14 05:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0019_sem_semmarks_semstudentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='Update', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='Update', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(default='Update', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(default='Update', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='Update', help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='student',
            name='pph',
            field=phone_field.models.PhoneField(blank=True, default='Update', help_text='Contact phone number', max_length=31),
        ),
    ]
