# Generated by Django 3.0.3 on 2020-05-14 05:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_auto_20200514_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='Update', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='Update', max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='Update', help_text='Contact phone number', max_length=31),
        ),
    ]
